
import { Subject, SyllabusItem } from './types';

export const SSC_SYLLABUS_2026: SyllabusItem[] = [
  // --- বাংলা ১ম পত্র (Bangla 1st - Code: 101) ---
  // গদ্য (Prose)
  { id: 'bn1-g01', subject: Subject.BANGLA_1ST, chapterNumber: 1, chapterTitle: 'শুভা', topics: [] },
  { id: 'bn1-g02', subject: Subject.BANGLA_1ST, chapterNumber: 2, chapterTitle: 'বই পড়া', topics: [] },
  { id: 'bn1-g03', subject: Subject.BANGLA_1ST, chapterNumber: 3, chapterTitle: 'অভাগীর স্বর্গ', topics: [] },
  { id: 'bn1-g04', subject: Subject.BANGLA_1ST, chapterNumber: 4, chapterTitle: 'পল্লীসাহিত্য', topics: [] },
  { id: 'bn1-g05', subject: Subject.BANGLA_1ST, chapterNumber: 5, chapterTitle: 'আম আঁটির ভেপু', topics: [] },
  { id: 'bn1-g06', subject: Subject.BANGLA_1ST, chapterNumber: 6, chapterTitle: 'মানুষ মুহম্মদ (স:)', topics: [] },
  { id: 'bn1-g07', subject: Subject.BANGLA_1ST, chapterNumber: 7, chapterTitle: 'নিমগাছ', topics: [] },
  { id: 'bn1-g08', subject: Subject.BANGLA_1ST, chapterNumber: 8, chapterTitle: 'শিক্ষা ও মনুষ্যত্ব', topics: [] },
  { id: 'bn1-g09', subject: Subject.BANGLA_1ST, chapterNumber: 9, chapterTitle: 'প্রবাস বন্ধু', topics: [] },
  { id: 'bn1-g10', subject: Subject.BANGLA_1ST, chapterNumber: 10, chapterTitle: 'মমতাদি', topics: [] },
  { id: 'bn1-g11', subject: Subject.BANGLA_1ST, chapterNumber: 11, chapterTitle: 'একাত্তরের দিনগুলি', topics: [] },
  { id: 'bn1-g12', subject: Subject.BANGLA_1ST, chapterNumber: 12, chapterTitle: 'সাহিত্যের রূপ ও রীতি', topics: [] },
  // কবিতা (Poetry)
  { id: 'bn1-k01', subject: Subject.BANGLA_1ST, chapterNumber: 13, chapterTitle: 'বঙ্গবাণী', topics: [] },
  { id: 'bn1-k02', subject: Subject.BANGLA_1ST, chapterNumber: 14, chapterTitle: 'কপোতাক্ষ নদ', topics: [] },
  { id: 'bn1-k03', subject: Subject.BANGLA_1ST, chapterNumber: 15, chapterTitle: 'জীবন-সঙ্গীত', topics: [] },
  { id: 'bn1-k04', subject: Subject.BANGLA_1ST, chapterNumber: 16, chapterTitle: 'জুতা-আবিষ্কার', topics: [] },
  { id: 'bn1-k05', subject: Subject.BANGLA_1ST, chapterNumber: 17, chapterTitle: 'ঝর্ণার গান', topics: [] },
  { id: 'bn1-k06', subject: Subject.BANGLA_1ST, chapterNumber: 18, chapterTitle: 'মানুষ', topics: [] },
  { id: 'bn1-k07', subject: Subject.BANGLA_1ST, chapterNumber: 19, chapterTitle: 'পল্লিজননী', topics: [] },
  { id: 'bn1-k08', subject: Subject.BANGLA_1ST, chapterNumber: 20, chapterTitle: 'আশা', topics: [] },
  { id: 'bn1-k09', subject: Subject.BANGLA_1ST, chapterNumber: 21, chapterTitle: 'আমি কোনো আগন্তুক নই', topics: [] },
  { id: 'bn1-k10', subject: Subject.BANGLA_1ST, chapterNumber: 22, chapterTitle: 'তোমাকে পাওয়ার জন্য হে স্বাধীনতা', topics: [] },
  { id: 'bn1-k11', subject: Subject.BANGLA_1ST, chapterNumber: 23, chapterTitle: 'আমার পরিচয়', topics: [] },
  { id: 'bn1-k12', subject: Subject.BANGLA_1ST, chapterNumber: 24, chapterTitle: 'স্বাধীনতা এই শব্দটি কীভাবে আমাদের হলো', topics: [] },
  // সহপাঠ (Co-curricular)
  { id: 'bn1-s01', subject: Subject.BANGLA_1ST, chapterNumber: 25, chapterTitle: 'কাঁকতারুয়া (উপন্যাস)', topics: [] },
  { id: 'bn1-s02', subject: Subject.BANGLA_1ST, chapterNumber: 26, chapterTitle: 'বহিপীর (নাটক)', topics: [] },

  // --- বাংলা ২য় পত্র (Bangla 2nd - Code: 102) ---
  { id: 'bn2-c01', subject: Subject.BANGLA_2ND, chapterNumber: 1, chapterTitle: 'ভাষা ও বাংলা ভাষা', topics: [] },
  { id: 'bn2-c02', subject: Subject.BANGLA_2ND, chapterNumber: 2, chapterTitle: 'ধ্বনি ও বর্ণ', topics: [] },
  { id: 'bn2-c03', subject: Subject.BANGLA_2ND, chapterNumber: 3, chapterTitle: 'শব্দের গঠন', topics: [] },
  { id: 'bn2-c04', subject: Subject.BANGLA_2ND, chapterNumber: 4, chapterTitle: 'পদ ও পদাশ্রিত নির্দেশক', topics: [] },
  { id: 'bn2-c05', subject: Subject.BANGLA_2ND, chapterNumber: 5, chapterTitle: 'বাক্য প্রকরণ', topics: [] },
  { id: 'bn2-c06', subject: Subject.BANGLA_2ND, chapterNumber: 6, chapterTitle: 'সমাস ও উপসর্গ', topics: [] },
  { id: 'bn2-c07', subject: Subject.BANGLA_2ND, chapterNumber: 7, chapterTitle: 'কারক ও বিভক্তি', topics: [] },
  { id: 'bn2-c08', subject: Subject.BANGLA_2ND, chapterNumber: 8, chapterTitle: 'চিঠিপত্র ও দরখাস্ত', topics: [] },
  { id: 'bn2-c09', subject: Subject.BANGLA_2ND, chapterNumber: 9, chapterTitle: 'সারাংশ ও সারমর্ম', topics: [] },
  { id: 'bn2-c10', subject: Subject.BANGLA_2ND, chapterNumber: 10, chapterTitle: 'ভাব-সম্প্রসারণ', topics: [] },
  { id: 'bn2-c11', subject: Subject.BANGLA_2ND, chapterNumber: 11, chapterTitle: 'প্রবন্ধ রচনা', topics: [] },

  // --- English 1st Paper (Code: 107) ---
  { id: 'en1-u01', subject: Subject.ENGLISH_1ST, chapterNumber: 1, chapterTitle: 'Unit 1: Good Citizens', topics: [] },
  { id: 'en1-u02', subject: Subject.ENGLISH_1ST, chapterNumber: 2, chapterTitle: 'Unit 2: Pastimes', topics: [] },
  { id: 'en1-u03', subject: Subject.ENGLISH_1ST, chapterNumber: 3, chapterTitle: 'Unit 3: Events and Festivals', topics: [] },
  { id: 'en1-u04', subject: Subject.ENGLISH_1ST, chapterNumber: 4, chapterTitle: 'Unit 4: Are We Aware?', topics: [] },
  { id: 'en1-u05', subject: Subject.ENGLISH_1ST, chapterNumber: 5, chapterTitle: 'Unit 5: Nature and Environment', topics: [] },
  { id: 'en1-u07', subject: Subject.ENGLISH_1ST, chapterNumber: 7, chapterTitle: 'Unit 7: People Who Stand Out', topics: [] },
  { id: 'en1-u08', subject: Subject.ENGLISH_1ST, chapterNumber: 8, chapterTitle: 'Unit 8: World Heritage', topics: [] },
  { id: 'en1-u10', subject: Subject.ENGLISH_1ST, chapterNumber: 10, chapterTitle: 'Unit 10: Dreams', topics: [] },
  { id: 'en1-u11', subject: Subject.ENGLISH_1ST, chapterNumber: 11, chapterTitle: 'Unit 11: Renewable Energy', topics: [] },
  { id: 'en1-u12', subject: Subject.ENGLISH_1ST, chapterNumber: 12, chapterTitle: 'Unit 12: Roots', topics: [] },
  { id: 'en1-u13', subject: Subject.ENGLISH_1ST, chapterNumber: 13, chapterTitle: 'Unit 13: Media and e-Communication', topics: [] },

  // --- English 2nd Paper (Code: 108) ---
  { id: 'en2-g01', subject: Subject.ENGLISH_2ND, chapterNumber: 1, chapterTitle: 'Grammar: Parts of Speech', topics: [] },
  { id: 'en2-g02', subject: Subject.ENGLISH_2ND, chapterNumber: 2, chapterTitle: 'Grammar: Tense & Sentence', topics: [] },
  { id: 'en2-g03', subject: Subject.ENGLISH_2ND, chapterNumber: 3, chapterTitle: 'Grammar: Articles & Prepositions', topics: [] },
  { id: 'en2-g04', subject: Subject.ENGLISH_2ND, chapterNumber: 4, chapterTitle: 'Grammar: Right Form of Verbs', topics: [] },
  { id: 'en2-g05', subject: Subject.ENGLISH_2ND, chapterNumber: 5, chapterTitle: 'Grammar: Transformation of Sentences', topics: [] },
  { id: 'en2-g06', subject: Subject.ENGLISH_2ND, chapterNumber: 6, chapterTitle: 'Grammar: Narration', topics: [] },
  { id: 'en2-g07', subject: Subject.ENGLISH_2ND, chapterNumber: 7, chapterTitle: 'Grammar: Punctuation & Connectors', topics: [] },
  { id: 'en2-g08', subject: Subject.ENGLISH_2ND, chapterNumber: 8, chapterTitle: 'Writing: CV, Letters, Emails', topics: [] },
  { id: 'en2-g09', subject: Subject.ENGLISH_2ND, chapterNumber: 9, chapterTitle: 'Writing: Paragraph & Essay', topics: [] },

  // --- পদার্থবিজ্ঞান (Physics - Code: 136) ---
  { id: 'phy-01', subject: Subject.PHYSICS, chapterNumber: 1, chapterTitle: 'ভৌত রাশি ও পরিমাপ', topics: [] },
  { id: 'phy-02', subject: Subject.PHYSICS, chapterNumber: 2, chapterTitle: 'গতি', topics: [] },
  { id: 'phy-03', subject: Subject.PHYSICS, chapterNumber: 3, chapterTitle: 'বল', topics: [] },
  { id: 'phy-04', subject: Subject.PHYSICS, chapterNumber: 4, chapterTitle: 'কাজ, ক্ষমতা ও শক্তি', topics: [] },
  { id: 'phy-05', subject: Subject.PHYSICS, chapterNumber: 5, chapterTitle: 'পদার্থের অবস্থা ও চাপ', topics: [] },
  { id: 'phy-06', subject: Subject.PHYSICS, chapterNumber: 6, chapterTitle: 'বস্তুর ওপর তাপের প্রভাব', topics: [] },
  { id: 'phy-07', subject: Subject.PHYSICS, chapterNumber: 7, chapterTitle: 'তরঙ্গ ও শব্দ', topics: [] },
  { id: 'phy-08', subject: Subject.PHYSICS, chapterNumber: 8, chapterTitle: 'আলোর প্রতিফলন', topics: [] },
  { id: 'phy-09', subject: Subject.PHYSICS, chapterNumber: 9, chapterTitle: 'আলোর প্রতিসরণ', topics: [] },
  { id: 'phy-10', subject: Subject.PHYSICS, chapterNumber: 10, chapterTitle: 'স্থির তড়িৎ', topics: [] },
  { id: 'phy-11', subject: Subject.PHYSICS, chapterNumber: 11, chapterTitle: 'চল তড়িৎ', topics: [] },
  { id: 'phy-12', subject: Subject.PHYSICS, chapterNumber: 12, chapterTitle: 'বিদ্যুতের চৌম্বক ক্রিয়া', topics: [] },
  { id: 'phy-13', subject: Subject.PHYSICS, chapterNumber: 13, chapterTitle: 'আধুনিক পদার্থবিজ্ঞান ও ইলেকট্রনিক্স', topics: [] },
  { id: 'phy-14', subject: Subject.PHYSICS, chapterNumber: 14, chapterTitle: 'জীবন বাঁচাতে পদার্থবিজ্ঞান', topics: [] },

  // --- রসায়ন (Chemistry - Code: 137) ---
  { id: 'chem-01', subject: Subject.CHEMISTRY, chapterNumber: 1, chapterTitle: 'রসায়নের ধারণা', topics: [] },
  { id: 'chem-02', subject: Subject.CHEMISTRY, chapterNumber: 2, chapterTitle: 'পদার্থের অবস্থা', topics: [] },
  { id: 'chem-03', subject: Subject.CHEMISTRY, chapterNumber: 3, chapterTitle: 'পদার্থের গঠন', topics: [] },
  { id: 'chem-04', subject: Subject.CHEMISTRY, chapterNumber: 4, chapterTitle: 'পর্যায় সারণি', topics: [] },
  { id: 'chem-05', subject: Subject.CHEMISTRY, chapterNumber: 5, chapterTitle: 'রাসায়নিক বন্ধন', topics: [] },
  { id: 'chem-06', subject: Subject.CHEMISTRY, chapterNumber: 6, chapterTitle: 'মোলের ধারণা ও রাসায়নিক গণনা', topics: [] },
  { id: 'chem-07', subject: Subject.CHEMISTRY, chapterNumber: 7, chapterTitle: 'রাসায়নিক বিক্রিয়া', topics: [] },
  { id: 'chem-08', subject: Subject.CHEMISTRY, chapterNumber: 8, chapterTitle: 'রসায়ন ও শক্তি', topics: [] },
  { id: 'chem-09', subject: Subject.CHEMISTRY, chapterNumber: 9, chapterTitle: 'এসিড-ক্ষার সমতা', topics: [] },
  { id: 'chem-10', subject: Subject.CHEMISTRY, chapterNumber: 10, chapterTitle: 'খনিজ সম্পদ: ধাতু-অধাতু', topics: [] },
  { id: 'chem-11', subject: Subject.CHEMISTRY, chapterNumber: 11, chapterTitle: 'খনিজ সম্পদ: জীবাশ্ম', topics: [] },
  { id: 'chem-12', subject: Subject.CHEMISTRY, chapterNumber: 12, chapterTitle: 'আমাদের জীবনে রসায়ন', topics: [] },

  // --- জীববিজ্ঞান (Biology - Code: 138) ---
  { id: 'bio-01', subject: Subject.BIOLOGY, chapterNumber: 1, chapterTitle: 'জীবন পাঠ', topics: [] },
  { id: 'bio-02', subject: Subject.BIOLOGY, chapterNumber: 2, chapterTitle: 'জীবকোষ ও টিস্যু', topics: [] },
  { id: 'bio-03', subject: Subject.BIOLOGY, chapterNumber: 3, chapterTitle: 'কোষ বিভাজন', topics: [] },
  { id: 'bio-04', subject: Subject.BIOLOGY, chapterNumber: 4, chapterTitle: 'জীবনীশক্তি', topics: [] },
  { id: 'bio-05', subject: Subject.BIOLOGY, chapterNumber: 5, chapterTitle: 'খাদ্য, পুষ্টি এবং পরিপাক', topics: [] },
  { id: 'bio-06', subject: Subject.BIOLOGY, chapterNumber: 6, chapterTitle: 'জীবে পরিবহন', topics: [] },
  { id: 'bio-07', subject: Subject.BIOLOGY, chapterNumber: 7, chapterTitle: 'গ্যাসীয় বিনিময়', topics: [] },
  { id: 'bio-08', subject: Subject.BIOLOGY, chapterNumber: 8, chapterTitle: 'রেচন প্রক্রিয়া', topics: [] },
  { id: 'bio-09', subject: Subject.BIOLOGY, chapterNumber: 9, chapterTitle: 'দৃঢ়তা প্রদান ও চলন', topics: [] },
  { id: 'bio-10', subject: Subject.BIOLOGY, chapterNumber: 10, chapterTitle: 'সমন্বয়', topics: [] },
  { id: 'bio-11', subject: Subject.BIOLOGY, chapterNumber: 11, chapterTitle: 'জীবের প্রজনন', topics: [] },
  { id: 'bio-12', subject: Subject.BIOLOGY, chapterNumber: 12, chapterTitle: 'জীবের বংশগতি ও বিবর্তন', topics: [] },
  { id: 'bio-13', subject: Subject.BIOLOGY, chapterNumber: 13, chapterTitle: 'জীবের পরিবেশ', topics: [] },
  { id: 'bio-14', subject: Subject.BIOLOGY, chapterNumber: 14, chapterTitle: 'জীবপ্রযুক্তি', topics: [] },

  // --- সাধারণ গণিত (Math - Code: 109) ---
  { id: 'gm-01', subject: Subject.MATH, chapterNumber: 1, chapterTitle: 'বাস্তব সংখ্যা', topics: [] },
  { id: 'gm-02', subject: Subject.MATH, chapterNumber: 2, chapterTitle: 'সেট ও ফাংশন', topics: [] },
  { id: 'gm-03', subject: Subject.MATH, chapterNumber: 3, chapterTitle: 'বীজগাণিতিক রাশি', topics: [] },
  { id: 'gm-04', subject: Subject.MATH, chapterNumber: 4, chapterTitle: 'সূচক ও লগারিদম', topics: [] },
  { id: 'gm-05', subject: Subject.MATH, chapterNumber: 5, chapterTitle: 'এক চলকবিশিষ্ট সমীকরণ', topics: [] },
  { id: 'gm-06', subject: Subject.MATH, chapterNumber: 6, chapterTitle: 'রেখা, কোণ ও ত্রিভুজ', topics: [] },
  { id: 'gm-07', subject: Subject.MATH, chapterNumber: 7, chapterTitle: 'ব্যবহারিক জ্যামিতি', topics: [] },
  { id: 'gm-08', subject: Subject.MATH, chapterNumber: 8, chapterTitle: 'বৃত্ত', topics: [] },
  { id: 'gm-09', subject: Subject.MATH, chapterNumber: 9, chapterTitle: 'ত্রিকোণমিতিক অনুপাত', topics: [] },
  { id: 'gm-10', subject: Subject.MATH, chapterNumber: 10, chapterTitle: 'দূরত্ব ও উচ্চতা', topics: [] },
  { id: 'gm-11', subject: Subject.MATH, chapterNumber: 11, chapterTitle: 'বীজগাণিতিক অনুপাত ও সমানুপাত', topics: [] },
  { id: 'gm-12', subject: Subject.MATH, chapterNumber: 12, chapterTitle: 'দুই চলকবিশিষ্ট সরল সহসমীকরণ', topics: [] },
  { id: 'gm-13', subject: Subject.MATH, chapterNumber: 13, chapterTitle: 'সসীম ধারা', topics: [] },
  { id: 'gm-14', subject: Subject.MATH, chapterNumber: 14, chapterTitle: 'অনুপাত, সদৃশতা ও প্রতিসমতা', topics: [] },
  { id: 'gm-15', subject: Subject.MATH, chapterNumber: 15, chapterTitle: 'ক্ষেত্রফল সম্পর্কিত উপপাদ্য ও সম্পাদ্য', topics: [] },
  { id: 'gm-16', subject: Subject.MATH, chapterNumber: 16, chapterTitle: 'পরিমিতি', topics: [] },
  { id: 'gm-17', subject: Subject.MATH, chapterNumber: 17, chapterTitle: 'পরিসংখ্যান', topics: [] },

  // --- উচ্চতর গণিত (Higher Math - Code: 126) ---
  { id: 'hm-01', subject: Subject.HIGHER_MATH, chapterNumber: 1, chapterTitle: 'সেট ও ফাংশন', topics: [] },
  { id: 'hm-02', subject: Subject.HIGHER_MATH, chapterNumber: 2, chapterTitle: 'বীজগাণিতিক রাশি', topics: [] },
  { id: 'hm-03', subject: Subject.HIGHER_MATH, chapterNumber: 3, chapterTitle: 'জ্যামিতি', topics: [] },
  { id: 'hm-04', subject: Subject.HIGHER_MATH, chapterNumber: 4, chapterTitle: 'জ্যামিতিক অঙ্কন', topics: [] },
  { id: 'hm-05', subject: Subject.HIGHER_MATH, chapterNumber: 5, chapterTitle: 'সমীকরণ', topics: [] },
  { id: 'hm-06', subject: Subject.HIGHER_MATH, chapterNumber: 6, chapterTitle: 'অসমতা', topics: [] },
  { id: 'hm-07', subject: Subject.HIGHER_MATH, chapterNumber: 7, chapterTitle: 'অসীম ধারা', topics: [] },
  { id: 'hm-08', subject: Subject.HIGHER_MATH, chapterNumber: 8, chapterTitle: 'ত্রিকোণমিতি', topics: [] },
  { id: 'hm-09', subject: Subject.HIGHER_MATH, chapterNumber: 9, chapterTitle: 'সূচকীয় ও লগারিদমীয় ফাংশন', topics: [] },
  { id: 'hm-10', subject: Subject.HIGHER_MATH, chapterNumber: 10, chapterTitle: 'দ্বিপদী বিস্তৃতি', topics: [] },
  { id: 'hm-11', subject: Subject.HIGHER_MATH, chapterNumber: 11, chapterTitle: 'স্থানাঙ্ক জ্যামিতি', topics: [] },
  { id: 'hm-12', subject: Subject.HIGHER_MATH, chapterNumber: 12, chapterTitle: 'সমতলীয় ভেক্টর', topics: [] },
  { id: 'hm-13', subject: Subject.HIGHER_MATH, chapterNumber: 13, chapterTitle: 'ঘন জ্যামিতি', topics: [] },
  { id: 'hm-14', subject: Subject.HIGHER_MATH, chapterNumber: 14, chapterTitle: 'সম্ভাবনা', topics: [] },

  // --- ইতিহাস ও বিশ্বসভ্যতা (History - Code: 153) ---
  { id: 'hist-01', subject: Subject.HISTORY, chapterNumber: 1, chapterTitle: 'ইতিহাস পরিচিতি', topics: [] },
  { id: 'hist-02', subject: Subject.HISTORY, chapterNumber: 2, chapterTitle: 'বিশ্বসভ্যতা', topics: [] },
  { id: 'hist-03', subject: Subject.HISTORY, chapterNumber: 3, chapterTitle: 'প্রাচীন বাংলার জনপদ', topics: [] },
  { id: 'hist-04', subject: Subject.HISTORY, chapterNumber: 4, chapterTitle: 'প্রাচীন বাংলার রাজনৈতিক ইতিহাস', topics: [] },
  { id: 'hist-05', subject: Subject.HISTORY, chapterNumber: 5, chapterTitle: 'প্রাচীন বাংলার সামাজিক ও সাংস্কৃতিক ইতিহাস', topics: [] },
  { id: 'hist-06', subject: Subject.HISTORY, chapterNumber: 6, chapterTitle: 'মধ্যযুগের বাংলা (১২০৪-১৭৬৫)', topics: [] },
  { id: 'hist-07', subject: Subject.HISTORY, chapterNumber: 7, chapterTitle: 'নবাবী আমলে বাংলা', topics: [] },
  { id: 'hist-08', subject: Subject.HISTORY, chapterNumber: 8, chapterTitle: 'বাংলায় ইংরেজ শাসনের সূচনা', topics: [] },
  { id: 'hist-09', subject: Subject.HISTORY, chapterNumber: 9, chapterTitle: 'ইংরেজ শাসনামলে প্রতিরোধ আন্দোলন', topics: [] },
  { id: 'hist-10', subject: Subject.HISTORY, chapterNumber: 10, chapterTitle: 'সংস্কার আন্দোলন ও বিদ্রোহ', topics: [] },
  { id: 'hist-11', subject: Subject.HISTORY, chapterNumber: 11, chapterTitle: 'ভাষা আন্দোলন ও পরবর্তী রাজনৈতিক ঘটনাপ্রবাহ', topics: [] },
  { id: 'hist-12', subject: Subject.HISTORY, chapterNumber: 12, chapterTitle: 'সামরিক শাসন ও স্বাধিকার আন্দোলন (১৯৫৮-১৯৬৯)', topics: [] },
  { id: 'hist-13', subject: Subject.HISTORY, chapterNumber: 13, chapterTitle: 'সত্তরের নির্বাচন ও মুক্তিযুদ্ধ', topics: [] },
  { id: 'hist-14', subject: Subject.HISTORY, chapterNumber: 14, chapterTitle: 'বঙ্গবন্ধু শেখ মুজিবুর রহমানের শাসনকাল', topics: [] },
  { id: 'hist-15', subject: Subject.HISTORY, chapterNumber: 15, chapterTitle: 'বিশ্ব সভ্যতার প্রধান বৈপ্লবিক ঘটনাপ্রবাহ', topics: [] },

  // --- ভূগোল ও পরিবেশ (Geography - Code: 110) ---
  { id: 'geo-01', subject: Subject.GEOGRAPHY, chapterNumber: 1, chapterTitle: 'ভূগোল ও পরিবেশ', topics: [] },
  { id: 'geo-02', subject: Subject.GEOGRAPHY, chapterNumber: 2, chapterTitle: 'মহাবিশ্ব ও আমাদের পৃথিবী', topics: [] },
  { id: 'geo-03', subject: Subject.GEOGRAPHY, chapterNumber: 3, chapterTitle: 'মানচিত্র পঠন ও ব্যবহার', topics: [] },
  { id: 'geo-04', subject: Subject.GEOGRAPHY, chapterNumber: 4, chapterTitle: 'পৃথিবীর অভ্যন্তরীণ ও বাহ্যিক গঠন', topics: [] },
  { id: 'geo-05', subject: Subject.GEOGRAPHY, chapterNumber: 5, chapterTitle: 'বায়ুমণ্ডল', topics: [] },
  { id: 'geo-06', subject: Subject.GEOGRAPHY, chapterNumber: 6, chapterTitle: 'বারিমণ্ডল', topics: [] },
  { id: 'geo-07', subject: Subject.GEOGRAPHY, chapterNumber: 7, chapterTitle: 'জনসংখ্যা', topics: [] },
  { id: 'geo-08', subject: Subject.GEOGRAPHY, chapterNumber: 8, chapterTitle: 'মানব বসতি', topics: [] },
  { id: 'geo-09', subject: Subject.GEOGRAPHY, chapterNumber: 9, chapterTitle: 'সম্পদ ও শিল্প', topics: [] },
  { id: 'geo-10', subject: Subject.GEOGRAPHY, chapterNumber: 10, chapterTitle: 'বাংলাদেশের ভৌগোলিক বিবরণ', topics: [] },
  { id: 'geo-11', subject: Subject.GEOGRAPHY, chapterNumber: 11, chapterTitle: 'বাংলাদেশের সম্পদ ও শিল্প', topics: [] },
  { id: 'geo-12', subject: Subject.GEOGRAPHY, chapterNumber: 12, chapterTitle: 'যোগাযোগ ব্যবস্থা ও বাণিজ্য', topics: [] },
  { id: 'geo-13', subject: Subject.GEOGRAPHY, chapterNumber: 13, chapterTitle: 'পরিবেশের ভারসাম্য ও করণীয়', topics: [] },
  { id: 'geo-14', subject: Subject.GEOGRAPHY, chapterNumber: 14, chapterTitle: 'টেকসই উন্নয়ন অভীষ্ট (SDG)', topics: [] },

  // --- পৌরনীতি ও নাগরিকতা (Civics - Code: 140) ---
  { id: 'civ-01', subject: Subject.CIVICS, chapterNumber: 1, chapterTitle: 'পৌরনীতি ও নাগরিকতা', topics: [] },
  { id: 'civ-02', subject: Subject.CIVICS, chapterNumber: 2, chapterTitle: 'নাগরিক ও নাগরিকতা', topics: [] },
  { id: 'civ-03', subject: Subject.CIVICS, chapterNumber: 3, chapterTitle: 'আইন, স্বাধীনতা ও সাম্য', topics: [] },
  { id: 'civ-04', subject: Subject.CIVICS, chapterNumber: 4, chapterTitle: 'রাষ্ট্র ও সরকার ব্যবস্থা', topics: [] },
  { id: 'civ-05', subject: Subject.CIVICS, chapterNumber: 5, chapterTitle: 'সংবিধান', topics: [] },
  { id: 'civ-06', subject: Subject.CIVICS, chapterNumber: 6, chapterTitle: 'বাংলাদেশের সরকার ব্যবস্থা', topics: [] },
  { id: 'civ-07', subject: Subject.CIVICS, chapterNumber: 7, chapterTitle: 'গণতন্ত্রে রাজনৈতিক দল ও নির্বাচন', topics: [] },
  { id: 'civ-08', subject: Subject.CIVICS, chapterNumber: 8, chapterTitle: 'বাংলাদেশের স্থানীয় সরকার ব্যবস্থা', topics: [] },
  { id: 'civ-09', subject: Subject.CIVICS, chapterNumber: 9, chapterTitle: 'নাগরিক সমস্যা ও আমাদের করণীয়', topics: [] },
  { id: 'civ-10', subject: Subject.CIVICS, chapterNumber: 10, chapterTitle: 'গণতান্ত্রিক ব্যবস্থা ও রাজনৈতিক দল', topics: [] },
  { id: 'civ-11', subject: Subject.CIVICS, chapterNumber: 11, chapterTitle: 'আন্তর্জাতিক সংস্থা ও বাংলাদেশ', topics: [] },

  // --- বাংলাদেশ ও বিশ্বপরিচয় (BGS - Code: 150) ---
  { id: 'bgs-01', subject: Subject.BGS, chapterNumber: 1, chapterTitle: 'পূর্ব বাংলার আন্দোলন ও জাতীয়তাবাদের উত্থান', topics: [] },
  { id: 'bgs-02', subject: Subject.BGS, chapterNumber: 2, chapterTitle: 'স্বাধীন বাংলাদেশ', topics: [] },
  { id: 'bgs-03', subject: Subject.BGS, chapterNumber: 3, chapterTitle: 'সৌরজগৎ ও ভূমন্ডল', topics: [] },
  { id: 'bgs-04', subject: Subject.BGS, chapterNumber: 4, chapterTitle: 'বাংলাদেশের ভূপ্রকৃতি ও জলবায়ু', topics: [] },
  { id: 'bgs-05', subject: Subject.BGS, chapterNumber: 5, chapterTitle: 'বাংলাদেশের নদ-নদী ও প্রাকৃতিক সম্পদ', topics: [] },
  { id: 'bgs-06', subject: Subject.BGS, chapterNumber: 6, chapterTitle: 'রাষ্ট্র, নাগরিকতা ও আইন', topics: [] },
  { id: 'bgs-07', subject: Subject.BGS, chapterNumber: 7, chapterTitle: 'বাংলাদেশ সরকার ও প্রশাসন', topics: [] },
  { id: 'bgs-08', subject: Subject.BGS, chapterNumber: 8, chapterTitle: 'বাংলাদেশের গণতন্ত্র ও নির্বাচন', topics: [] },
  { id: 'bgs-09', subject: Subject.BGS, chapterNumber: 9, chapterTitle: 'জাতিসংঘ ও বাংলাদেশ', topics: [] },
  { id: 'bgs-10', subject: Subject.BGS, chapterNumber: 10, chapterTitle: 'টেকসই উন্নয়ন অভীষ্ট (SDG)', topics: [] },
  { id: 'bgs-11', subject: Subject.BGS, chapterNumber: 11, chapterTitle: 'জাতীয় সম্পদ ও অর্থনৈতিক ব্যবস্থা', topics: [] },
  { id: 'bgs-16', subject: Subject.BGS, chapterNumber: 16, chapterTitle: 'সামাজিক সমস্যা ও এর প্রতিকার', topics: [] },

  // --- সাধারণ বিজ্ঞান (General Science - Code: 127) ---
  { id: 'gs-01', subject: Subject.GENERAL_SCIENCE, chapterNumber: 1, chapterTitle: 'উন্নততর জীবনধারা', topics: [] },
  { id: 'gs-02', subject: Subject.GENERAL_SCIENCE, chapterNumber: 2, chapterTitle: 'জীবনের জন্য পানি', topics: [] },
  { id: 'gs-03', subject: Subject.GENERAL_SCIENCE, chapterNumber: 3, chapterTitle: 'হৃদযন্ত্রের যত কথা', topics: [] },
  { id: 'gs-04', subject: Subject.GENERAL_SCIENCE, chapterNumber: 4, chapterTitle: 'নবজীবনের সূচনা', topics: [] },
  { id: 'gs-05', subject: Subject.GENERAL_SCIENCE, chapterNumber: 5, chapterTitle: 'দেখতে হলে আলো চাই', topics: [] },
  { id: 'gs-06', subject: Subject.GENERAL_SCIENCE, chapterNumber: 6, chapterTitle: 'পলিমার', topics: [] },
  { id: 'gs-07', subject: Subject.GENERAL_SCIENCE, chapterNumber: 7, chapterTitle: 'অম্ল, ক্ষারক ও লবণের ব্যবহার', topics: [] },
  { id: 'gs-08', subject: Subject.GENERAL_SCIENCE, chapterNumber: 8, chapterTitle: 'আমাদের সম্পদ', topics: [] },
  { id: 'gs-10', subject: Subject.GENERAL_SCIENCE, chapterNumber: 10, chapterTitle: 'এসো বলকে জানি', topics: [] },
  { id: 'gs-12', subject: Subject.GENERAL_SCIENCE, chapterNumber: 12, chapterTitle: 'বিদ্যুৎ ও আধুনিক প্রযুক্তি', topics: [] },

  // --- তথ্য ও যোগাযোগ প্রযুক্তি (ICT - Code: 154) ---
  { id: 'ict-01', subject: Subject.ICT, chapterNumber: 1, chapterTitle: 'তথ্য প্রযুক্তি ও আমাদের বাংলাদেশ', topics: [] },
  { id: 'ict-02', subject: Subject.ICT, chapterNumber: 2, chapterTitle: 'কম্পিউটার ও ব্যবহারকারীর নিরাপত্তা', topics: [] },
  { id: 'ict-03', subject: Subject.ICT, chapterNumber: 3, chapterTitle: 'আমার শিক্ষায় ইন্টারনেট', topics: [] },
  { id: 'ict-04', subject: Subject.ICT, chapterNumber: 4, chapterTitle: 'আমার লেখালেখি ও হিসাব', topics: [] },
  { id: 'ict-05', subject: Subject.ICT, chapterNumber: 5, chapterTitle: 'মাল্টিমিডিয়া ও গ্রাফিক্স', topics: [] },
  { id: 'ict-06', subject: Subject.ICT, chapterNumber: 6, chapterTitle: 'ডেটাবেজ এর ব্যবহার', topics: [] },

  // --- ইসলাম ও নৈতিক শিক্ষা (Religion - Code: 111) ---
  { id: 'rel-01', subject: Subject.RELIGION, chapterNumber: 1, chapterTitle: 'আকাইদ ও নৈতিক জীবন', topics: [] },
  { id: 'rel-02', subject: Subject.RELIGION, chapterNumber: 2, chapterTitle: 'শরীয়তের উৎস', topics: [] },
  { id: 'rel-03', subject: Subject.RELIGION, chapterNumber: 3, chapterTitle: 'ইবাদত', topics: [] },
  { id: 'rel-04', subject: Subject.RELIGION, chapterNumber: 4, chapterTitle: 'আখলাক', topics: [] },
  { id: 'rel-05', subject: Subject.RELIGION, chapterNumber: 5, chapterTitle: 'আদর্শ জীবনচরিত', topics: [] }
];

export const GRADES = [
  { range: [80, 100], grade: 'A+' },
  { range: [70, 79], grade: 'A' },
  { range: [60, 69], grade: 'A-' },
  { range: [50, 59], grade: 'B' },
  { range: [40, 49], grade: 'C' },
  { range: [33, 39], grade: 'D' },
  { range: [0, 32], grade: 'F' }
];
